version: '2'
services: 

  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file:
      - docker/base.env
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    networks:
      - backend

  web:
    build:
      context: ./
      dockerfile: docker/web/Dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8081:80
    networks:
      - frontend
      - backend

  database:
    image: mysql:latest
    volumes:
      - ~/.ds/data/mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=vagrant"
    ports:
      - 33061:3306
    networks:
      - backend

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

volumes:
   mysql:
    driver: "local"
